### ISSUE TITLE
Int overflow+crash in escape_control_and_add_styles() for a large file

### ISSUE THREAD

**Issue by c4eater** [little-dude/xi-tui#112]
Hi,

Here is what happens when I try to open a file with ~65k (around 0xffff) or more symbols:

```
(bash) # for f in {0..781}; do echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX line $f" >> test.dat; done
(bash) # xi-term ~/test.dat 2>error.log
(bash) # # xi-term opens and immediately crashes
(bash) # cat error.log

thread 'tokio-runtime-worker-3' panicked at 'attempt to add with overflow', src/widgets/view/view.rs:324:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'tokio-runtime-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', src/libcore/result.rs:997:5
```

I traced the output logs of xrl and found that xrl is receiving the full contents of test.dat from xi-core, concatenated into a single very long line with "\n"'s (which is definitely unexpected; this huge line is added to linecache without any splitting):

```
2019-09-25T01:44:12.393891388+03:00 DEBUG xrl::protocol::endpoint - handling message from remote peer Notification(Notification { method: "update", params: Object({"update": Object({"annotations": Array([Object({"n": Number(1), "payloads": Null, "ranges": Array([Array([Number(0), Number(0), Number(0), Number(0)])]), "type": String("selection")})]), "ops": Array([Object({"lines": Array([Object({"cursor": Array([Number(0)]), "ln": Number(1), "styles": Array([]), "text": String("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX line 0\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX line 1\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX line 2\n <...SNIP...>XXXXXXXXX line 781\n")})]), "n": Number(1), "op": String("ins")}), Object({"n": Number(771), "op": String("invalidate")})]), "pristine": Bool(true)}), "view_id": String("view-id-2")}) })
```

No surprise that view.rs encounters an u16 overflow here.

Disclaimer: I still don't know whether this is the problem of xi-term, xrl, or xi-core.

Thanks

**Comment by c4eater** [comment]
Cannot reproduce this anymore. This was either a local misconfiguration or a xi-core (?) issue fixed in the past two weeks.
