### ISSUE TITLE
panick at runtime

### ISSUE THREAD

**Issue by Cyrix126** [little-dude/xi-tui#116]
## Details
-Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- rustc 1.65.0 (897e37553 2022-11-02)
- installed from source

`thread 'tokio-runtime-worker-0' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /home/lm/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/internal.rs:493:59
stack backtrace:
   0:     0x55b7468c88f0 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b7468c88f0 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b7468c88f0 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55b7468c88f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55b7468ed7fe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x55b7468c5975 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x55b7468ca2c3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55b7468ca2c3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55b7468ca2c3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x55b7468c9faf - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x55b7468ca96a - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x55b7468ca821 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:     0x55b7468c8d9c - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55b7468ca582 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x55b74676a6f3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x55b74676a5bd - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:     0x55b74682483a - <crossbeam_epoch::internal::Local as crossbeam_epoch::sync::list::IsElement<crossbeam_epoch::internal::Local>>::entry_of::h2d33d5788ee0257b
  17:     0x55b746824c24 - crossbeam_epoch::collector::Collector::register::hbc53afbaae10ffb3
  18:     0x55b74681e2bd - std::thread::local::lazy::LazyKeyInner<T>::initialize::h3bb7a88b522f6243
  19:     0x55b74681e694 - crossbeam_deque::Stealer<T>::steal_batch_and_pop::hf3b1f347d058cea2
  20:     0x55b746812e33 - tokio_threadpool::worker::Worker::run::h94b6a411945fb145
  21:     0x55b74680652b - tokio_trace_core::dispatcher::with_default::h1cf17342ee37eeb7
  22:     0x55b7467ff74f - std::thread::local::LocalKey<T>::with::h63be62a179d5a083
  23:     0x55b7467ff8f3 - std::thread::local::LocalKey<T>::with::hadcee93c82a6a398
  24:     0x55b746800f97 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h504195ce6181288b
  25:     0x55b746815d8c - std::thread::local::LocalKey<T>::with::haeaad6fe5d807462
  26:     0x55b746815ea8 - std::thread::local::LocalKey<T>::with::hdbdb231a93bacdab
  27:     0x55b74681d397 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c553417cecc0568
  28:     0x55b74681c5be - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc777b5ca596c2879
  29:     0x55b7468cf033 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  30:     0x55b7468cf033 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  31:     0x55b7468cf033 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7f2d2292a609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  33:     0x7f2d226fa133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  34:                0x0 - <unknown>`

**Comment by nunotexbsd** [comment]
Same here (FreeBSD, rust 1.65.0).

It's a pity because this was one of the first programs that I ported to FreeBSD to test xi-editor core.
It will be nice that this project do some maintainance updates like xi-editor is doing.

All frontend apps around xi-editor are dying?

**Comment by omendezmorales** [comment]
+1 (on Ubuntu 22.10, and using rustc 1.64.0) , I read about this project elsewhere , and after watching [Ralph's intro](https://youtu.be/4FbQre9VQLI), I thought it was worth trying it.
