### ISSUE TITLE
failed to spawn xi-core on Ubuntu 18.04

### ISSUE THREAD

**Issue by MtDersvan** [little-dude/xi-tui#86]
Hi, followed the instructions but keep getting this error:
~~~
    Finished release [optimized] target(s) in 0.07s                             
     Running `target/release/xi-term dummy`
thread 'main' panicked at 'failed to spawn xi-core: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
~~~
Any suggestions or a manual?
Thanks

EDIT:
~~~
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: xrl::core::spawn
  10: xi_term::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
~~~

**Comment by patrickisgreene** [comment]
Have you installed xi-core? xi-term expect's the binary to be located somewhere in $PATH, you can install it like this
```
git clone https://github.com/xi-editor/xi-editor.git
cd xi-editor
cargo build --release
sudo mv target/release/xi-core /usr/bin/
```

**Comment by MtDersvan** [comment]
Thanks, @bytebuddha `sudo mv target/release/xi-core /usr/bin/` - helped

**Comment by little-dude** [comment]
Fwiw I find copying stuff into `/usr/bin` a bit brutal. A better solution would be to make sure your `PATH` contains the directory that contains the `xi-core` binary that is built by cargo. If you use `cargo install` instead of `cargo build`, cargo should put the binaries under `~/.cargo/bin`, so you can just add this to your bashrc:

```
export PATH="${HOME}/.cargo/bin:${PATH}"
```

**Comment by patrickisgreene** [comment]
@little-dude that's a much better idea, maybe we should add a note in the readme about adding ~/.cargo/bin to path?

**Comment by MtDersvan** [comment]
Thanks, now I got it. I have added `~/.cargo/bin` to the `PATH` initially, but used `cargo build` mentioned in the `xi-editor` repo.

**Comment by little-dude** [comment]
@bytebuddha yeah I'll do that.

**Comment by little-dude** [comment]
> I have added `~/.cargo/bin` to the `PATH` initially, but used `cargo build` mentioned in the xi-editor repo.

Yeah that's confusing indeed. Definitely worth a note in the README.
